function mage_help() {
  echo -e "${BOLD}CMD Options:${RESET}"
  echo -e "- ${BLUE}info${RESET} (Show base config for store)"
  echo -e "- ${BLUE}self-update${RESET} (Update mage)"
  echo -e "- ${BLUE}stores${RESET} (Show all stores)"
  echo -e "- ${BLUE}open${RESET} (Open store in browser)"
  echo -e "- ${BLUE}watch${RESET} (Run cache-clean.js from mageTV)"
  echo -e "- ${BLUE}purge${RESET} (Purge all static assets)"
  echo -e "- ${BLUE}new admin${RESET} (Create new admin user)"
  echo -e "- ${BLUE}new customer${RESET} (Create new customer)"
  echo -e "- ${BLUE}new theme${RESET} (Create new theme)"
  echo -e "- ${BLUE}new module${RESET} (Create new module)"
  echo -e "- ${BLUE}new i18n${RESET} (Create new translations)"
  echo -e "- ${BLUE}add sample${RESET} (Add sample data)"
  echo -e "- ${BLUE}add hyva${RESET} (Add Hyva Theme)"
  echo -e "- ${BLUE}add checkout${RESET} (Add Hyva Checkout)"
  echo -e "- ${BLUE}set config${RESET} (Set Magento Configs)"
  echo -e "- ${BLUE}set hyva${RESET} (Set hyva default theme)"
  echo -e "- ${BLUE}set theme${RESET} (Set theme)"
  echo -e "- ${BLUE}build${RESET} (Run setup:static-content:deploy with common defaults)"
  echo -e "- ${BLUE}run${RESET} (Run magerun2)"
  echo -e "\n${ITALIC}Anything else will run ${BLUE}bin/magento${RESET}"
  echo -e "${ITALIC}To see these copmmand again, run ${BLUE}mage --help${RESET}"
}
